# -*- coding: utf-8 -*-
"""Box plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wxPN8wUtZPntTknM97web7Ep2xUnqQWH
"""

import matplotlib.pyplot as plt
import numpy as np

# Given dataset
dataset = [32, 14, 5, 67, 88, 9, 11, 13, 5, 61, 7, 5]

# Calculate quartiles and IQR manually
sorted_data = sorted(dataset)
Q1 = np.percentile(sorted_data, 25)
Q2 = np.percentile(sorted_data, 50)
Q3 = np.percentile(sorted_data, 75)
IQR = Q3 - Q1

# Find outliers
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = [x for x in sorted_data if x < lower_bound or x > upper_bound]

# Display box plot
plt.boxplot(dataset)
plt.title('Box Plot')
plt.show()

# Display calculated values
print(f"Q1 (25th percentile): {Q1}")
print(f"Q2 (50th percentile - Median): {Q2}")
print(f"Q3 (75th percentile): {Q3}")
print(f"IQR (Interquartile Range): {IQR}")
print(f"Outliers: {outliers}")